---
# Patches ImageTragick problem
- name: Apply common configration to all nodes
  hosts: all
  sudo: yes
  # Uncomment to apply update one server at a time
  # serial: 1
  tasks:
    - name: "Copy ImageMagick Policy.xml (CHECK AND MAKE SURE THAT YOU ARE NOT OVERWRITING ANY MANUAL CHANGES)"
      copy: src=policy.xml dest=/etc/ImageMagick/policy.xml owner=root group=root mode=0644

